#
# Copyright (C) 2015 Altera Corporation <www.altera.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= clock_manager_a10.o fpga_manager_a10.o misc_a10.o reset_manager_a10.o
obj-y	+= sdram_a10.o
